sudo: required
dist: trusty
group: deprecated-2017Q4
language: java
jdk:
  - oraclejdk8

before_script:
  - '
    mysql -uroot -e "create database if not exists demo character set utf8"
    '

script:
  - '
    sudo apt-get install libaio1
    '
  - '
    ./mvnw clean install sonar:sonar
        -Dspring.profiles.active="ci"
        -Dshishamo.embedded.mysql=false
        -Dsonar.host.url="https://sonarcloud.io"
        -Dsonar.organization="yo1000-github"
        -Dsonar.login="${SONAR_QUBE_TOKEN}"
        -Pembedded
    '
