version: 2
jobs:
  build:

    working_directory: ~/shishamo

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - restore_cache:
          key: shishamo-{{ checksum "pom.xml" }}

      - run: ./mvnw clean integration-test -Dspring.profiles.active=circleci -Dshishamo.embedded.mysql=false

      - save_cache:
          paths:
            - ~/.m2
          key: shishamo-{{ checksum "pom.xml" }}


      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/shishamo.jar
